trigger:
- master
- development

jobs:
- job: Xcode_test
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    maxParallel: 10
    matrix:
      xcode101:
        DEVELOPER_DIR: /Applications/Xcode_10.1.app
  steps:
  - task: Xcode@5
    inputs:
      actions: 'test'
      scheme: 'TriforkSwiftExtensions'
      sdk: 'iphonesimulator'
      configuration: 'Debug'
      xcWorkspacePath: '**/TriforkSwiftExtensions/TriforkSwiftExtensions.xcodeproj'
      xcodeVersion: 'specifyPath'
      xcodeDeveloperDir: '/Applications/Xcode_10.1.app'
      signingOption: 'auto'
      useXcpretty: true
      publishJUnitResults: true
      destinationSimulators: 'iPhone 7'
      destinationTypeOption: 'simulators'
      destinationPlatformOption: 'iOS'

- job: Danger
  pool:
    vmImage: 'macOS-10.13'
    variables:
      DEVELOPER_DIR: /Applications/Xcode_10.1.app
  steps:
    - script: echo $DANGER_GITHUB_API_TOKEN
      displayName: Token test
    - script: bundle update --bundler
      displayName: Update bundler
    - script: bundle install
      displayName: bundle install
    - script: bundle exec danger --verbose
      displayName: Run Danger

      env:
        DANGER_GITHUB_API_TOKEN: $(DANGER_GITHUB_API_TOKEN)
