trigger:
- master
- development

jobs:
- job: Xcode_test
  pool:
    vmImage: 'macOS-10.14'
  strategy:
    maxParallel: 10
    matrix:
      xcode102:
        DEVELOPER_DIR: /Applications/Xcode_10.2.app
      xcode11:
        DEVELOPER_DIR: /Applications/Xcode_11.app  
      xcode111:
        DEVELOPER_DIR: /Applications/Xcode_11.1.app
      xcode1121:
        DEVELOPER_DIR: /Applications/Xcode_11.2.1.app
  steps:
  - task: Xcode@5
    inputs:
      actions: 'test'
      scheme: 'TriforkSwiftExtensions'
      sdk: 'iphonesimulator'
      configuration: 'Debug'
      xcWorkspacePath: '**/TriforkSwiftExtensions/TriforkSwiftExtensions.xcodeproj'
      xcodeVersion: 'specifyPath'
      xcodeDeveloperDir: $(DEVELOPER_DIR)
      signingOption: 'auto'
      useXcpretty: true
      publishJUnitResults: true
      destinationSimulators: 'iPhone 8'
      destinationTypeOption: 'simulators'
      destinationPlatformOption: 'iOS'

- job: Danger
  pool:
    vmImage: 'macOS-10.14'
    variables:
      DEVELOPER_DIR: /Applications/Xcode_10.2.app
  steps:
    - script: bundle update --bundler
      displayName: Update bundler
    - script: bundle install
      displayName: bundle install
    - script: bundle exec danger --verbose
      displayName: Run Danger

      env:
        DANGER_GITHUB_API_TOKEN: $(DANGER_GITHUB_API_TOKEN)
